#!/usr/bin/env python3

import requests
import sys

CF_API_KEY = 'xxxx'
CF_EMAIL = 'xxxx'
CF_WS_URL = 'https://www.cloudflare.com/api_json.html'
IPFY_WS_URL = 'https://api.ipify.org?format=json'


def cfrequest(mail, tkn, a, **kwargs):
    params = {
        'email': mail,
        'tkn': tkn,
        'a': a
    }
    params.update(kwargs)
    return requests.post(CF_WS_URL, params=params).json()


def myip():
    return requests.get(IPFY_WS_URL).json()['ip']


if __name__ == "__main__":
    if len(sys.argv) == 2:
        dyndns = sys.argv[1]
        zone = '.'.join(dyndns.split('.')[1:])
    else:
        print("Il faut le domaine en args 1")
        sys.exit(1)

    try:
        resp_getdns = cfrequest(CF_EMAIL, CF_API_KEY, 'rec_load_all', z=zone)
    except Exception as ex:
        print("Oops: %s" % ex)
    else:
        for entry in resp_getdns['response']['recs']['objs']:
            if entry['name'] == dyndns:
                name = entry['name']
                ipcf = entry['content']
                iploc = myip()
                if iploc != ipcf:
                    print("Diff d'ip (loc:%s cf:%s dns:%s)" % (iploc, ipcf, name))
                    print("Demande de changement auprès de cf ...")
                    iddnsrecord = entry['rec_id']
                    try:
                        resp_updns = cfrequest(CF_EMAIL, CF_API_KEY, 'rec_edit',
                                               id=iddnsrecord,
                                               z=zone,
                                               type='A',
                                               name=dyndns.split('.')[0],
                                               content=iploc,
                                               service_mode=0,
                                               ttl=1)
                    except Exception as ex:
                        print('Oops: %s' % ex)
                        sys.exit(1)
                    else:
                        if resp_getdns['result'] == "success":
                            print("Modification ok")
                            sys.exit(0)
                        else:
                            print("%s: %s" % (resp_updns['result'], resp_updns['msg']))
                            sys.exit(1)
